### PR TITLE
[IMP] stock_location_orderpoint: Incremental run of cron rules

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@mt-software-de @jbaudoux

**Comment by rousseldenis** [comment]
@lmignon

**Review by lmignon — APPROVED** [review]

**Review by jbaudoux — APPROVED** [review]
LGTM

**Comment by rousseldenis** [comment]
@mt-software-de You can backport this to 14 ?

**Comment by mt-software-de** [comment]
> @mt-software-de You can backport this to 14 ?

Thx for the improvment, currently i don't have time to backport this. :-(

**Pull request merged**
