### PR TITLE
[16.0][MIG] stock_orderpoint_move_link

### PR DESCRIPTION
**Pull request by TDu**
This module is coming from stock-logistics-warehouse and this pr https://github.com/OCA/stock-logistics-warehouse/pull/1505

### CODE REVIEW

**Comment by TDu** [comment]
https://github.com/OCA/stock-logistics-orderpoint/pull/1

**Comment by rousseldenis** [comment]
@TDu Could you rebase ?

**Comment by TDu** [comment]
@rousseldenis Rebase done.

**Review by rousseldenis — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
