### PR TITLE
[FIX] stock_location_orderpoint: Use correct method in job function

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Review by mt-software-de — APPROVED** [review]
Thanks. 
Could you as well change the docstring of https://github.com/OCA/stock-logistics-orderpoint/blob/8a3eea818c829a29ec88bb0591948277a27ef979/stock_location_orderpoint/models/stock_move.py#L60

**Comment by rousseldenis** [comment]
@mt-software-de @jbaudoux

**Review by jbaudoux — APPROVED** [review]

**Comment by rousseldenis** [comment]
> @rousseldenis The merge process could not be finalized, because command `twine upload --repository-url https://upload.pypi.org/legacy/ -u __token__ odoo_addon_stock_location_orderpoint-16.0.1.1.2-py3-none-any.whl` failed with output:
> 
> ```
> Uploading distributions to https://upload.pypi.org/legacy/
> Uploading odoo_addon_stock_location_orderpoint-16.0.1.1.2-py3-none-any.whl
> �[?25l
> �[2K�[35m  0%�[0m �[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━�[0m �[32m0.0/61.3 kB�[0m • �[36m--:--�[0m • �[31m?�[0m
> �[2K�[35m  0%�[0m �[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━�[0m �[32m0.0/61.3 kB�[0m • �[36m--:--�[0m • �[31m?�[0m
> �[2K�[35m  0%�[0m �[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━�[0m �[32m0.0/61.3 kB�[0m • �[36m--:--�[0m • �[31m?�[0m
> �[2K�[35m100%�[0m �[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━�[0m �[32m61.3/61.3 kB�[0m • �[33m00:00�[0m • �[31m75.2 MB/s�[0m
> �[2K�[35m100%�[0m �[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━�[0m �[32m61.3/61.3 kB�[0m • �[33m00:00�[0m • �[31m75.2 MB/s�[0m
> �[2K�[35m100%�[0m �[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━�[0m �[32m61.3/61.3 kB�[0m • �[33m00:00�[0m • �[31m75.2 MB/s�[0m
> �[2K�[35m100%�[0m �[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━�[0m �[32m61.3/61.3 kB�[0m • �[33m00:00�[0m • �[31m75.2 MB/s�[0m
> �[2K�[35m100%�[0m �[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━�[0m �[32m61.3/61.3 kB�[0m • �[33m00:00�[0m • �[31m75.2 MB/s�[0m
> �[?25h�[33mWARNING �[0m Error during upload. Retry with the --verbose option for more details. 
> �[31mERROR   �[0m HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
>          'description-content-type' must be one of ['text/plain', 'text/x-rst', 
>          'text/markdown'], not ''. See                                          
>          https://packaging.python.org/specifications/core-metadata for more     
>          information.                                                           
> ```

@sbidoul Should we investigate this ? pypi is not updated:

https://pypi.org/project/odoo-addon-stock-location-orderpoint/#history

**Comment by sbidoul** [comment]
Probably a PyPI issue (Looks like a PyPI issue: https://github.com/pypi/warehouse/issues/15628#issuecomment-2007297634). Can you please check tomorrow?

**Pull request merged**
