### PR TITLE
[16.0][MIG]stock_orderpoint_route: migration to `16.0`

### PR DESCRIPTION
**Pull request by PicchiSeba**
This module was originally from [https://github.com/OCA/stock-logistics-warehouse/tree/14.0/](https://github.com/OCA/stock-logistics-warehouse/tree/14.0/) but for `16.0` it has been moved to this repo

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by yvaucher — APPROVED** [review]
LGTM

Thanks you @PicchiSeba

**Comment by yvaucher** [comment]
@PicchiSeba seems the merge failed due to the following error:

```
2024-09-30 13:42:03,203 259 ERROR odoo odoo.addons.stock_location_orderpoint.tests.test_location_orderpoint: ERROR: TestLocationOrderpoint.test_cron_replenishment
Traceback (most recent call last):
  File "/__w/stock-logistics-orderpoint/stock-logistics-orderpoint/stock_location_orderpoint/tests/test_location_orderpoint.py", line 99, in test_cron_replenishment
    tomorrow = now.replace(day=now.day + 1)
ValueError: day is out of range for month
```

I would advice to use freezegun to get a fixed date in the tests. It most likely fails because today is the 30 september and tomorrow is not the 31 of september ;) 

Or you can more simply use `fields.Date.add(today, days=1)` (thanks @sebalix for the tip)

**Comment by PicchiSeba** [comment]
> @PicchiSeba seems the merge failed due to the following error:
> 
> ```
> 2024-09-30 13:42:03,203 259 ERROR odoo odoo.addons.stock_location_orderpoint.tests.test_location_orderpoint: ERROR: TestLocationOrderpoint.test_cron_replenishment
> Traceback (most recent call last):
>   File "/__w/stock-logistics-orderpoint/stock-logistics-orderpoint/stock_location_orderpoint/tests/test_location_orderpoint.py", line 99, in test_cron_replenishment
>     tomorrow = now.replace(day=now.day + 1)
> ValueError: day is out of range for month
> ```
> 
> I would advice to use freezegun to get a fixed date in the tests. It most likely fails because today is the 30 september and tomorrow is not the 31 of september ;)
> 
> Or you can more simply use `fields.Date.add(today, days=1)` (thanks @sebalix for the tip)

The problem lies in the `stock_location_orderpoint` module. In particular line 99 of tests/test_location_orderpoint.py
https://github.com/OCA/stock-logistics-orderpoint/blob/e387e1e00784331237940f584901b67aa157e103/stock_location_orderpoint/tests/test_location_orderpoint.py#L99
This statement will **always** fail if we test on the last day of the month

**Comment by PicchiSeba** [comment]
@yvaucher we can merge this now. Later in the day I will fix the base module test

**Pull request merged**
