### PR TITLE
[16.0] [MIG] stock_orderpoint_purchase_link

### PR DESCRIPTION
**Pull request by TDu**
This module is coming from stock-logistics-warehouse and this pr https://github.com/OCA/stock-logistics-warehouse/pull/1506

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Comment by LoisRForgeFlow** [comment]
- Depends on https://github.com/OCA/stock-logistics-orderpoint/pull/1.

**Comment by LoisRForgeFlow** [comment]
@TDu You can now remove the temporary commit

**Comment by TDu** [comment]
> @TDu You can now remove the temporary commit

Done.

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
